image: Visual Studio 2017

platform:
- x86
- x64

configuration:
  - Debug
  - Release
  
environment:
  matrix:
  - SHARED: ON
    POSTFIXNAME: MD
    POSTVCPKGNAME:
    
  - SHARED: OFF
    POSTFIXNAME: MT
    POSTVCPKGNAME: -static
        
    
matrix:
  fast_finish: true

install:  
  - ps: wget https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi -outfile "VCForPython27.msi"
  - start /wait msiexec /i VCForPython27.msi /quiet /qn /norestart
  - pip install autobahntestsuite
  - mkdir deps
  - cd deps
  - set CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.1.-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip
  - move cmake-* cmake # Move to a version-agnostic directory
  - set PATH=%cd%\cmake\bin;%PATH%
  - cmake --version
  - cd ..
  - mkdir build
  - cd build
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1
  - .\vcpkg integrate install
  - .\vcpkg install zlib:%PLATFORM%-windows%POSTVCPKGNAME% openssl:%PLATFORM%-windows%POSTVCPKGNAME%
  - ps: if($env:POSTFIXNAME -eq 'MD') {
          Invoke-Expression "&.\vcpkg.exe export zlib:$($env:PLATFORM)-windows$($env:POSTVCPKGNAME) openssl:$($env:PLATFORM)-windows$($env:POSTVCPKGNAME) --raw";
          move vcpkg-export-* vcpkg-export;
          set-location "vcpkg-export\installed\$($env:PLATFORM)-windows$($env:POSTVCPKGNAME)\";
          if($env:configuration -eq 'Debug') {
            set-location debug;
            Invoke-Expression "&7z a vc140_$($env:configuration)_$($env:PLATFORM)_$($env:POSTFIXNAME).zip -i!bin\* -i!lib\*";
            cd ..;
            Invoke-Expression "&7z a -tzip debug\vc140_$($env:configuration)_$($env:PLATFORM)_$($env:POSTFIXNAME).zip -i!include\*";
          } else {
            Invoke-Expression "&7z a vc140_$($env:configuration)_$($env:PLATFORM)_$($env:POSTFIXNAME).zip -i!bin\* -i!lib\*";
            Invoke-Expression "&7z a -tzip vc140_$($env:configuration)_$($env:PLATFORM)_$($env:POSTFIXNAME).zip -i!include\*";
          }  
          Copy-Item *.zip C:\projects\websocket-lite\build\
        }
  
build_script:
  - set-location C:\projects\websocket-lite\build\
  - if %platform%==x86 set generator=Visual Studio 15 2017
  - if %platform%==x64 set generator=Visual Studio 15 2017 Win64
  - if %POSTFIXNAME%==MT set VCPKGFLAGS=-DVCPKG_TARGET_TRIPLET=%platform%-windows-static
  - cmd: echo %generator% %SHARED% %configuration% 
  - cmd: cmake "-DCMAKE_TOOLCHAIN_FILE=%cd%\vcpkg\scripts\buildsystems\vcpkg.cmake" -G"%generator%" %VCPKGFLAGS% -DBUILD_SHARED_LIBS=%SHARED% -DCMAKE_INSTALL_PREFIX=./output .. 
  - cmd: cmake --build . --target INSTALL --config %configuration%
  - 7z a -tzip vc140_%configuration%_%PLATFORM%_%POSTFIXNAME%.zip  -i!%APPVEYOR_BUILD_FOLDER%\build\output\*
  - appveyor PushArtifact vc140_%configuration%_%PLATFORM%_%POSTFIXNAME%.zip
  
deploy:
  provider: GitHub
  auth_token:
    secure: WCGi6SXwa6VaPyLH6fZCrmTix+e2FA3zwzhNg8dSf3EdrcecGIR3Z0qG/vssOdfA 
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true 
