image: Visual Studio 2017

configuration:
  - Debug
  
clone_folder: c:\projects\proj

clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

cache:		
  - c:\projects\build\vcpkg -> appveyor.yml		
 
platform:
- x86

install:  
  - ps: wget https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi -outfile "VCForPython27.msi"
  - start /wait msiexec /i c:\projects\proj\VCForPython27.msi /quiet /qn /norestart
  - pip install autobahntestsuite
  - ps: If ($env:Platform -Match "x86"){ $env:CMAKE_ARCH="" } Else { $env:CMAKE_ARCH=" Win64"}
  - cd c:\projects
  - IF NOT EXIST c:\projects\build mkdir build
  - cd build
  - IF NOT EXIST c:\projects\build\vcpkg git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - IF NOT EXIST c:\projects\build\vcpkg\installed\x86-windows powershell -exec bypass scripts\bootstrap.ps1
  - IF NOT EXIST c:\projects\build\vcpkg\installed\x86-windows .\vcpkg install zlib openssl
  - cd c:\projects\proj
  - mkdir build
  - cd build
  - cmake "-DCMAKE_TOOLCHAIN_FILE=c:\projects\build\vcpkg\scripts\buildsystems\vcpkg.cmake" .. 
  
build_script:
  - cmake --build .
  
test_script:
  - ctest -V -C Debug 
